### ISSUE TITLE
Update supported version for WoTLKC please

### ISSUE THREAD

**Issue by Smexhy** [anzz1/TacoTip#9]
Addon says it's out of date, could you possibly change the version the next udpate please?

**Comment by anzz1** [comment]
Added FAQ entry:

***If you get "Addon out of date" error***  
Press ESC for Menu -> Addons -> Check: [X] Load out of date AddOns  

![out-of-date-addon-menu-small](https://user-images.githubusercontent.com/13628128/199223990-17896046-3407-472d-be70-b78fc42ae905.jpg)

**Comment by anzz1** [comment]
#### "Not in Range"

- "Not in range" error text was fixed way back in v0.1.5 https://github.com/anzz1/TacoTip/commit/88efc38bbd074e831b720b49cfae1d25f38376f5

- "Not in range" error speech was fixed in v0.2.8 https://github.com/anzz1/TacoTip/commit/babc3143e73b03807e66d5bee36d23a37649e1fd
 This one slipped the radar for so long because most people don't play with error speech on, so this went unnoticed.

In any case, that bug is not even caused by the addon, but rather a bug in Blizzard API (it does not respect the showError flag being set to false, as it should, as is stated per the documentation).  

We have fixed it for them though.  
So having TacoTip enabled (more specifically, any addon using [LibClassicInspector](https://github.com/anzz1/TacoTip/blob/master/Libs/LibClassicInspector/LibClassicInspector.lua)) will also fix the Blizzard's bug for other addons too.

---

#### "Addon is out of date"

The "out-of-date" message is just a nag which means literally nothing.  

As people do not only play Wrath, but also Wrath PTR, Classic Era and Classic Era PTR, and as especially the PTR versions receive updates sometimes in very quick succession, I will not be pushing version updates every other day which serve literally no other purpose than to change a number in the .toc files, to remove a completely unnecessary nag message which Blizzard decided to add for some incomprehensible reason.  

It is also very easily disabled by just checking a simple box. Literally takes seconds to do.

If you are annoyed by it though, no one will stop you from editing the .toc file yourself and changing the interface version everytime a new client update gets pushed. By all means, go for it. I am not going to, though, as disabling the nag is way faster and easier.
